---
apiVersion: v1
kind: Service
metadata:
  name: nginx-external
spec:
  type: NodePort
  selector:
    app: nginx-external
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30107

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-external
  labels:
    app: nginx-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-external
  template:
    metadata:
      labels:
        app: nginx-external
    spec:
      containers:
      - name: nginx-external
        image: nginx:1.14.2
        ports:
        - containerPort: 80
